name: pull-request-integration

on:
  pull_request_target:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:

  integration:
    # Require reviewers for this environment
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    environment: integration

    runs-on: ubuntu-latest

    steps:
      - name: Perform testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          # ansible-core-version:
          git-checkout-ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request
          pre-test-cmd: >-  # Configure integration test run
            HEALTHCHECKSIO_API_TOKEN=${{ secrets.HEALTHCHECKSIO_API_TOKEN }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          python-version: 3.9
          target-python-version: 3.8
          testing-type: integration
          test-deps: community.general

  integration_self_hosted:
    # Require reviewers for this environment
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    environment: integration_self_hosted

    runs-on: ubuntu-latest

    steps:
      - name: Perform testing self-hosted
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          # ansible-core-version:
          git-checkout-ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request
          pre-test-cmd: >-  # Configure integration test run
            MANAGEMENT_API_TOKEN=${{ secrets.MANAGEMENT_API_TOKEN }}
            MANAGEMENT_API_BASE_URL=${{ secrets.MANAGEMENT_API_BASE_URL }}
            PING_API_BASE_URL=${{ secrets.PING_API_BASE_URL }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          python-version: 3.9
          target-python-version: 3.8
          testing-type: integration
          test-deps: community.general
